Update add-on description to be in line with other add-ons
zigbee2mqtt/hassio-zigbee2mqtt pull request #104
Opened 2021-05-08 13:32 UTC by CodeFinder2

This slightly changes the subtitle as displayed in the Supervisor's add-on page. According to other add-ons, it should briefly explain what the add-on does.

#### Checklist
- [x] PR done against `dev` branch
- [ ] Updated `common/Dockerfile` with new version
- [ ] Updated `zigbee2mqtt/CHANGELOG.md` file with new changes
- [ ] Updated `zigbee2mqtt/DOCS.md` with any changes
- [ ] Add any new configuration options to `zigbee2mqtt/config.json` and `zigbee2mqtt-edge/config.json`.

2021-05-19 10:56 UTC, afoeder requested changes
Hi, please fix the typos, otherwise it's good to go for me 👍

2021-05-19 10:56 UTC, afoeder commented on zigbee2mqtt/config.json
> +  "description": "Use your Zigbee devices without the vendors bridge or gateway",
* ZigBee
* vendor's

2021-05-19 11:05 UTC, CodeFinder2 commented on zigbee2mqtt/config.json
> +  "description": "Use your Zigbee devices without the vendors bridge or gateway",
Thanks for your suggestions, done! :-)

2021-05-19 11:55 UTC, afoeder approved these changes

2021-06-04 10:08 UTC, CodeFinder2 commented
?

2021-06-04 15:14 UTC, CodeFinder2 commented
Why has this been closed without any explanation / merge? @Koenkk

2021-06-04 19:43 UTC, Koenkk commented
@CodeFinder2 sorry, seems this was done automatically on the 1.19.1-1 release. @ciotlosm can you review this mr?

2021-08-12 15:54 UTC, ciotlosm commented
Closing and re-opening to re-trigger checks.

2021-08-17 08:00 UTC, ciotlosm approved these changes

2021-08-17 08:00 UTC, merged